# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4062400323a470cc5bb0625a198a5e92d5b944771e5373627e06e55bd823966c6444f6e2627c0410bad0dcfb1ec6d0be5664960a105080e850b77e6a41f0d12

test:
  secret_key_base: d85ae6ed268df72392b27a08f1e7ed84bc4b682f1cc3acff929927a4c15251cb65674beda19fd957f67d772a758c3ebc925578af33a428db5563f2ca3de403f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
